### ISSUE TITLE
Remove quotations marks requirement for selectors

### ISSUE THREAD

**Issue by danielakhterov** [yamafaktory/jql#56] opened 2020-08-11 08:26 UTC
Personally, I expect `jq 'message' text.json` to work, but I'm required to do `jq '"message"' text.json` instead which seems kinda pointless. Is this a potential feature/QoL improvement?

**Comment by yamafaktory** [comment] 2020-08-11 08:55
I guess you mean `jql` not `jq` which is another tool :)

The reason is that people tend to forget about special characters in JSON https://github.com/yamafaktory/jql#special-characters

`jq` doesn't work out-of-the-box for those corner cases and you need to use some wizardry, see https://github.com/stedolan/jq/issues/140. That's why `jql` does it like that, it always works, no matter what you inject but at the cost of having single quotes around.

I'm closing it as I have no plan to change the way it was designed.

**Closed by yamafaktory** 2020-08-11 08:55 UTC

**Comment by HenkPoley** [comment] 2020-08-28 14:38
Anyways, on your benchmark page, the last jql item is not equivalent to jq due to the quotes requirement: https://github.com/yamafaktory/jql/blob/master/PERFORMANCE.md

**Comment by yamafaktory** [comment] 2020-08-28 14:56
@HenkPoley good point! it should be `echo '{ "foo": "bar" }' | jql '."foo"'`... will fix!
